apiVersion: 1

groups:
  - orgId: 1
    name: backend-alerts
    folder: Backend Alerts   
    interval: 1m
    rules:
      - uid: backend-down
        title: BackendDown
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="backend"} == 0
        noDataState: Alerting
        execErrState: Alerting
