
# AWS region
aws_region = "value"

# Networking
vpc_cidr = "10.0.0.0/16"
availability_zones = [
  "us-east-1a",
  "us-east-1b"
]

# EC2 configuration
ec2_ami       = "ami-0b6c6ebed2801a5cb"
key_name      = "test-key" 


domain_name = "delightdavid.online"

certificate_arn = "arn:aws:axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" #add your own acm generated by aws
hosted_zone_id= "Z0XXXXXXXXX" #add your own hosted_zone_id

subdomain="xxx" #add a subdomain of your choice

instance_type    = "t3.micro"
desired_capacity = 2
max_size         = 4
min_size         = 2

docdb_instance_class = "db.t3.medium"
docdb_instance_count = 1

docdb_username = "admin"
docdb_password = "supersecurepassword"

db_name = "appdb"