-- ============================================================================
-- Production-Grade Database Initialization Script
-- Database: minishop
-- Description:
--   - Creates application database with utf8mb4 support
--   - Creates dedicated application user with least-privilege access
--   - Creates normalized tables with constraints and indexes
--   - Seeds initial application data idempotently
--
-- Notes:
--   - Replace the placeholder password before deployment.
--   - Store credentials in AWS Secrets Manager, not in source control.
-- ============================================================================

-- --------------------------------------------------------------------------
-- Create database
-- --------------------------------------------------------------------------


USE minishop;

-- --------------------------------------------------------------------------
-- Create dedicated application user (least privilege)
-- Replace 'CHANGE_ME_STRONG_PASSWORD' with a secure password.
-- In production, this should be rotated and stored in AWS Secrets Manager.
-- --------------------------------------------------------------------------
CREATE USER IF NOT EXISTS 'minishop_app'@'%' IDENTIFIED BY 'CHANGE_ME_STRONG_PASSWORD';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX
ON minishop.* TO 'minishop_app'@'%';

FLUSH PRIVILEGES;

-- --------------------------------------------------------------------------
-- Products table
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    sku VARCHAR(100) NULL,
    price DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT chk_products_price CHECK (price >= 0)
) ENGINE=InnoDB;

-- Index to support product search by name
CREATE INDEX idx_products_name ON products (name);

-- --------------------------------------------------------------------------
-- Users table
-- IMPORTANT:
--   Passwords must be stored as hashes (bcrypt/argon2), never plain text.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
) ENGINE=InnoDB;

-- --------------------------------------------------------------------------
-- Seed products (idempotent)
-- Uses unique SKU so rerunning the script updates existing records.
-- --------------------------------------------------------------------------
INSERT INTO products (name, description, sku, price, currency)
VALUES
    ('Laptop', 'High-performance laptop', 'SKU-LAPTOP-001', 1200.00, 'USD'),
    ('Phone', 'Latest smartphone', 'SKU-PHONE-001', 800.00, 'USD'),
    ('Headphones', 'Noise-cancelling headphones', 'SKU-HEADPHONES-001', 150.00, 'USD')
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description),
    price = VALUES(price),
    currency = VALUES(currency),
    is_active = TRUE;

-- --------------------------------------------------------------------------
-- Seed admin user (idempotent)
-- Replace password hash with a real bcrypt/argon2 hash generated by the app.
-- Example placeholder hash below is for demonstration only.
-- --------------------------------------------------------------------------
INSERT INTO users (
    username,
    email,
    password_hash,
    is_active,
    is_admin
)
VALUES (
    'admin',
    'admin@example.com',
    '$2b$12$REPLACE_WITH_REAL_BCRYPT_HASH',
    TRUE,
    TRUE
)
ON DUPLICATE KEY UPDATE
    email = VALUES(email),
    is_active = TRUE,
    is_admin = TRUE;

-- --------------------------------------------------------------------------
-- Optional verification
-- --------------------------------------------------------------------------
SELECT 'Database initialized successfully' AS status;